apiVersion: v1
kind: Service
metadata:
  namespace: moovd-api
  name: moovd-psycho-educatie-cms-service
imagePullSecrets:
  - name: registry-credentials
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: moovd-psycho-educatie-cms
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moovd-psycho-educatie-cms
  namespace: moovd-api
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: moovd-psycho-educatie-cms
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moovd-psycho-educatie-cms
    spec:
      containers:
        - name: moovd-psycho-educatie-cms-qa
          image: registry.gitlab.com/moovd-intern/products/psycho-education/psycho-education-cms:development
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
